application: testgcp-996
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: angularApp/app/index.html
  upload: angularApp/app/(.*\.html)

- url: /post
  static_files: templates/index.html
  upload: templates/(.*\.html)

- url: /js
  static_dir: angularApp/app/js

- url: /css
  static_dir: angularApp/app/css

- url: /img
  static_dir: angularApp/app/img

- url: /partials
  static_dir: angularApp/app/partials

- url: /.*
  script: _go_app
